### ISSUE TITLE
SSL certificate renewal script

### ISSUE THREAD

**Issue by vishi24** [beckn/protocol-server#110]
## Description

The current protocol server implementation features a script designed to handle the renewal of SSL certificates obtained from the election script. Unfortunately, there have been instances where this script has encountered failures. It is crucial to ascertain the effectiveness of this script in renewing SSL certificates from Let's Encrypt.

To validate the script, run the script to renew the SSL certificate and see if the certificate is updated or not. 

Also, list the possible cases in which the script may fail. These reasons should be documented in the Readme file under FAQ section.

## Goals

- [ ] Validate the SSL renewal certificate.

## Expected Outcome

SSL certificate renewal script should work properly.

## Acceptance Criteria

- [ ] Script is checked thoroughly.
- [ ] Possible reasons for failure are listed,

**Comment by prasad-takale-eminds** [comment]
We have a Jenkins job to update the SSL certificate on all the servers. 
Jenkins Job URLs: 
https://jenkins.becknprotocol.io/job/DevOps/job/ssl-cert-renew-prod/ 
https://jenkins.becknprotocol.io/job/DevOps/job/ssl-cert-renew-prod-ec2user/
