### ISSUE TITLE
update the docker hub with the new protocol server image (network policy)

### ISSUE THREAD

**Issue by faizmagic** [beckn/protocol-server#114]
Once the changes for the network policy are done on the protocol server, create a new image for the protocol server and push the image to the docker hub account. This image will be tagged as the latest and used by ONIX for creating a protocol server container.

**Comment by vbabuEM** [comment]
Link to the video that shows that this is working
https://drive.google.com/file/d/1C01_AAJ2Wl-PnQhJ-PycQd5QDyka9yYP/view?usp=sharing
