### ISSUE TITLE
Configuration document is not available in the attached link - https://github.com/beckn/protocol-server/Configuration_Guide.md

### ISSUE THREAD

**Issue by sagarinpursue** [beckn/protocol-server#12]

**Comment by sagarinpursue** [comment]
![image](https://user-images.githubusercontent.com/12951874/196635108-5d244d17-073a-4cf0-853d-aea24820a851.png)

**Comment by darshansk** [comment]
This was an error in the hyperlink. The issue has been fixed in commit ea24e3e. 

The correct hyperlink is : https://github.com/beckn/protocol-server/blob/v2/guides/configuration-guide.md
