### ISSUE TITLE
Getting Error in Setting up BAP and BPP applications  in Local Environment

### ISSUE THREAD

**Issue by Vansh1190** [beckn/protocol-server#120]
My mongoDB and Redis is connected but i am getting this error.
and it is showing on my screen multiple times.

Kindly provide me a solution.

![image (4)](https://github.com/beckn/protocol-server/assets/77226791/0b9d85f7-8008-4fe1-92e1-638205edb5cc)

**Comment by faizmagic** [comment]
@vbabuEM, can you check this

**Comment by vbabuEM** [comment]
It is something to do with his cloud provider. @faizmagic

**Comment by vbabuEM** [comment]
@Vansh1190 , has this been sorted out? If so, can you please leave a brief solution. Thanks

**Comment by vbabuEM** [comment]
@Vansh1190 , can this issue be closed?

**Comment by Vansh1190** [comment]
Yes sure
