### ISSUE TITLE
The endpoint /logs without query parameter is returning a wierd message

### ISSUE THREAD

**Issue by vbabuEM** [beckn/protocol-server#121]
**Problem**
When we go to /logs endpoint on Protocol Server, currently it gives the following:
{"message":{"ack":{"status":"NACK"}},"error":{}}

The /logs with query parameters work. For example /logs?type=info

**Requirement**
/logs endpoint without query parameters should show the entire log without any filter(same as debug filter). The filtering that happens with query parameters should remain as is.

**Test**
Goto /logs - All logs should be displayed (same as debug filter)
Goto /logs?type=error - Only logs with severity "error" should be shown
Similar for type=info, warn, debug and http

**Comment by vbabuEM** [comment]
@faizmagic, @vishi24  - This is the issue to fix the /logs endpoint without any filters.

**Comment by shreyvishal** [comment]
Current Status: Development is done, Tested in local and Raised PR.
PR - [Link to Develop](https://github.com/beckn/protocol-server/pull/137)

Attaching Screenshot for testing done on local

cc: @vbabuEM @faizmagic @viraj89
