### ISSUE TITLE
CI/CD setup - Protocol server Staging environment

### ISSUE THREAD

**Issue by vishi24** [beckn/protocol-server#124]
## Description
There is no CI/CD setup for the protocol server  (https://github.com/beckn/protocol-server) staging environment. Create a CI/CD for the protocol server staging branch to the protocol server staging environment. When the develop branch code is merged to staging branch, it should be deployed on the staging environment.

## Goals

- [ ] Working CI/CD for the protocol server staging branch to the Strapi BPP staging environment.

## Expected Outcome
Working CI/CD pipeline for protocol server staging branch.
When the code is pushed to the staging branch, it should be deployed to the staging environment.

## Acceptance Criteria

- [ ] Working CI/CD pipeline for protocol server staging branch.

## Implementation Details

NA

## Mockups / Wireframes

NA

---

[Please note that the below section of the ticket **** has to be in the format as mentioned as it is key to enabling proper listing of the project.**** Please only choose the options mentioned under the headings wherever applicable.]

### Product Name

NA

### Project Name

NA

### Organization Name:

FIDE

### Domain

NA

### Tech Skills Needed:

DevOps - Jenkins
Github
### Complexity

Medium

### Category

Deployment

### Sub Category

CI/CD

**Comment by vbabuEM** [comment]
Same as #131
