### ISSUE TITLE
CI/CD set up - Protocol Server Develop branch to protocol server development environment

### ISSUE THREAD

**Issue by vishi24** [beckn/protocol-server#125]
## Description
There is no CI/CD setup for the protocol server  (https://github.com/beckn/protocol-server) development environment. Create a CI/CD for the protocol server develop branch to the protocol server development environment. When the developer pushes the code, it should be deployed on the development environment.

## Goals

- [ ] Working CI/CD for the protocol server development branch to the Strapi BPP development environment.

## Expected Outcome
Working CI/CD pipeline for protocol sevrer develop branch.
When the code is pushed to the development branch, it should be deployed to the development environment.

## Acceptance Criteria

- [ ] Working CI/CD pipeline for protocol server develop branch.

## Implementation Details

NA

## Mockups / Wireframes

NA

---

[Please note that the below section of the ticket **** has to be in the format as mentioned as it is key to enabling proper listing of the project.**** Please only choose the options mentioned under the headings wherever applicable.]

### Product Name

NA

### Project Name

NA

### Organization Name:

FIDE

### Domain

NA

### Tech Skills Needed:

DevOps - Jenkins
Github
### Complexity

Medium

### Category

Deployment

### Sub Category

CI/CD

**Comment by em-tpt-bbandi** [comment]
Created a CI/CD for the protocol server 



![Image](https://github.com/user-attachments/assets/e89f9434-4bf2-4c8a-ad96-bf5a888b6a71)

**Comment by prasad-takale-eminds** [comment]
We don't deploy the PS directly after the build we deploy it on the respective env whenever developer confirm for the deployment.
