### ISSUE TITLE
Test cases for unsolicited changes

### ISSUE THREAD

**Issue by PritiEM** [beckn/protocol-server#129]
## Description
This ticket outlines various test cases for handling unsolicited messages within the Beckn ecosystem.

## Expected Outcome
A comprehensive set of test cases is defined to cover various scenarios related to unsolicited messages. These test cases will ensure that the Beckn system can effectively handle unsolicited messages and maintain its functionality and reliability.

## Test Cases
1. If normal message comes before TTL, it should be received by BAP and queue should be cleared after 10 mins.
2. If normal message comes after TTL, It should not be sent ahead and dropped after logging correct message, queue should be cleared after 10 mins.
3. If normal message is never responded back, queue should be cleared after 10 mins.
4. If normal message comes after 10 mins, it is considered as unsolicited and should be sent to unsolicited webhook.
5. While BAP is waiting for solicited message of a type and in between comes unsolicited message of same type, BAP should not get confused between solicited and unsolicited messages.
6. If unsolicited message sent by BPP, it should reach the webhook.
7. Handling of unsolicited message while BAP server down.
8. Handling of unsolicited message while unsolicited webhook server down.

## Mockups / Wireframes
NA

## Product Name
Beckn

## Domain
Mobility

## Tech Skills Needed
Strapi plugins, Message Queue Management, Webhook Integration

## Complexity
High

## Category
Testing

## Sub Category
Unsolicited Message Handling

**Comment by em-abee** [comment]
Done
