### ISSUE TITLE
Licenses at repo and readme are different in V2

### ISSUE THREAD

**Issue by core-wg-admin** [beckn/protocol-server#13]
While the repository shows MIT license, the README mentions GNU public license.

As this software is a digital public good, requesting you to change it to MIT License as GNU license will restrict proprietary platforms from redistributing it.

**Comment by core-wg-admin** [comment]
Linked a PR that contains fix to the issue (among other fixes). Please close this once that is merged.

**Comment by thisissandeepkumar** [comment]
The Branch has now been merged.
