### ISSUE TITLE
Deployment of protocol server on dev and staging

### ISSUE THREAD

**Issue by em-abee** [beckn/protocol-server#131]
## Description
The deployment process for the protocol server on both development and staging environments needs to be streamlined to ensure consistency and reliability across different stages of the release pipeline.

## Goals
- [ ] Establish a robust deployment process for the protocol server on dev.
- [ ] Replicate the deployment process for the staging environment.
- [ ] Minimize downtime during deployment.

## Expected Outcome
A seamless and error-free deployment process for the protocol server that works consistently across dev and staging environments.

## Acceptance Criteria
- [ ] Successful deployment on dev with no critical issues.
- [ ] Successful replication of the deployment process on staging.
- [ ] Documentation of the deployment steps and any scripts used.
- [ ] Verification from QA that the deployment meets all operational requirements.

## Mockups / Wireframes
NA

## Product Name
**Beckn**

## Domain
GCL

## Tech Skills Needed
Backend Engineering 

## Complexity
Medium

## Category
Deployment

## Sub Category
Server Configuration and Management

**Comment by prasad-takale-eminds** [comment]
We have successfully redeployed Protocol Server (BAP and BPP) and generic client layer.

**Comment by viraj89** [comment]
@prasad-takale-eminds - please add the correct screenshots and close this ticket.

**Comment by viraj89** [comment]
This is a duplicate for https://github.com/beckn/beckn-ui-workspace/issues/829 - for staging. 

This is a duplicate for https://github.com/beckn/beckn-ui-workspace/issues/300  - for dev. 

This ticket to be closed.
