### ISSUE TITLE
BOC Env - Create Registry and Gateway Domain Names for BOC using AWS EC2 Instance

### ISSUE THREAD

**Issue by viraj89** [beckn/protocol-server#132]
### Description
The goal of this ticket is to create domain names for the Beckn Online Community Environment (BOC) using an AWS EC2 instance. The domains to be created are as follows:

- Registry: `https://registry.becknprotocol.io`
- Gateway: `https://gateway.becknprotocol.io`

Update all this information on this Confluence Page [here](https://fide-official.atlassian.net/wiki/spaces/EC/pages/318603265/Beckn+One+Ver+1.1+Infra+landscape+-+BOC). 

### Goals
- [ ] Create the Registry domain name for BOC using the AWS EC2 instance.
- [ ] Create the Gateway domain name for BOC using the AWS EC2 instance.

### Expected Outcome
Successful creation of the Registry and Gateway domain names for BOC using the AWS EC2 instance.

### Acceptance Criteria
- [ ] The Registry domain name `https://registry.becknprotocol.io` is successfully created.
- [ ] The Gateway domain name `https://gateway.becknprotocol.io` is successfully created.

Add the following information as necessary:
- [ ] Screenshot of the running instance with the instance details and IP address.
- [ ] Screenshot of the Route 53 configuration - Domain name mapping.
- [ ] Screenshot of NGINX configuration (http, https)
- [ ] Screenshot of successful installation of the component through appropriate tool.
- [ ] Screenshot after updating the [Confluence Page](https://fide-official.atlassian.net/wiki/spaces/EC/pages/318603265/Beckn+One+Ver+1.1+Infra+landscape+-+BOC) with the instance details.

### Mockups / Wireframes
Not applicable

### Product Name
Beckn, Beckn Online Community Environment (BOC)

### Domain
Infrastructure

### Tech Skills Needed
- AWS EC2
- Domain Name Configuration

### Complexity
Low

### Category
Infrastructure

### Sub Category
Domain Name Configuration

**Comment by prasad-takale-eminds** [comment]
We have deployed the BOC registry and gateway using the Beckn Onix script.  Also, we have migrated the existing DB of the registry and gateway. 
We haven't changed the URL for the gateway and registry. 

Screenshots of the same
Onix Installations.
Registry


![Image](https://github.com/beckn/protocol-server/assets/84436945/77d8b5f7-3084-4732-84d8-f1ee3d92538b)


Gateway


![Image](https://github.com/beckn/protocol-server/assets/84436945/cd3c1c84-94dd-4b24-8a71-18a12d435d37)


Confluence


![Image](https://github.com/beckn/protocol-server/assets/84436945/f03be0d5-e888-460c-8abb-36b4c092d123)
