### ISSUE TITLE
BOC Env - Add BAP Domain Names for the Protocol Server

### ISSUE THREAD

**Issue by viraj89** [beckn/protocol-server#133]
### Description
The goal of this ticket is to add BAP domain names for the Protocol Server using an AWS EC2 instance. The domains to be added are as follows:

- Client: `https://ps-bap-client.becknprotocol.io`
- Network: `https://ps-bap-network.becknprotocol.io`
- 
Update all this information on this Confluence Page [here](https://fide-official.atlassian.net/wiki/spaces/EC/pages/318603265/Beckn+One+Ver+1.1+Infra+landscape+-+BOC). 

### Goals
- [ ] Add the BAP Client domain name for the Protocol Server using the AWS EC2 instance.
- [ ] Add the BAP Network domain name for the Protocol Server using the AWS EC2 instance.

### Expected Outcome
Successful addition of the BAP Client and Network domain names for the Protocol Server using the AWS EC2 instance.

### Acceptance Criteria
- [ ] The BAP Client domain name `https://ps-bap-client.becknprotocol.io` is successfully added.
- [ ] The BAP Network domain name `https://ps-bap-network.becknprotocol.io` is successfully added.

Add the following information as necessary:
- [ ] Screenshot of the running instance with the instance details and IP address.
- [ ] Screenshot of the Route 53 configuration - Domain name mapping.
- [ ] Screenshot of NGINX configuration (http, https)
- [ ] Screenshot of successful installation of the component through appropriate tool.
- [ ] Screenshot after updating the [Confluence Page](https://fide-official.atlassian.net/wiki/spaces/EC/pages/318603265/Beckn+One+Ver+1.1+Infra+landscape+-+BOC) with the instance details.

### Mockups / Wireframes
Not applicable

### Product Name
Beckn

### Domain
Protocol Server 

### Tech Skills Needed
- AWS EC2
- Domain Name Configuration

### Complexity
Low

### Category
Infrastructure

### Sub Category
Domain Name Configuration

**Comment by prasad-takale-eminds** [comment]
We have installed the BOC BAP protocol Server with the beckn Onix script on the existing EC2 instances.
