### ISSUE TITLE
Migrate Core Protocol Spec to OpenAPI 3.1 

### ISSUE THREAD

**Issue by viraj89** [beckn/protocol-server#139]
### Description
Migrate the Core Protocol Specification to OpenAPI Specification 3.1 format while adding necessary validations. This will enhance the clarity, consistency, and maintainability of the specification document.

### Goals
- [x] Migrate the Core Protocol Specification to OpenAPI Specification 3.1.
- [x] Add Examples for each APIs

### Expected Outcome
Successfully migrate the Core Protocol Specification to OpenAPI Specification 3.1 with added example, ensuring improved clarity and accuracy.

### Acceptance Criteria
- [x] Core Protocol Specification is migrated to OpenAPI Specification 3.1.
- [x] examples are added for each API.

### Product Name
Beckn

### Domain
Protocol Specification 

### Tech Skills Needed
- OpenAPI Specification 3.1
- Validation Implementation

### Complexity
Medium

### Category
Specification Management

### Sub Category
Migration and Validation

**Comment by emmayank** [comment]
**3rd May, 2024**, Time Spent : 8 hrs
1. Read about Open API Specification 3.1

**Comment by emmayank** [comment]
6th May, 2024, Time Spent : 8 hrs

1. changed the openapi version to 3.1.0
2. No Breaking changes observed
3. Started Adding Validations

`Blocker/ Issue: New Swagger Editor for OAS3.1 is not working properly as expected, debugging if it is issue in the YAML or the UI Tool.`

**Comment by emmayank** [comment]
8th May, 2024 , Time Spent : 8 hrs

1. Tried different Editors and Plugins to see if the issue still persists.
2. Later resolved the issue, by adding example in the reference schema


![Image](https://github.com/beckn/protocol-server/assets/112108963/2d4cc6eb-ab22-4705-8e0d-cd9787b75e59)

**Comment by emmayank** [comment]
**9th May, 2024, Time Spent: 10 hrs**
1. Added Example Directory in the Core Specification and 
2. Added Examples for search, on_search, select, on_select, confirm

**Comment by emmayank** [comment]
**10th May, 2024, Time Spent: 10 hrs**
1. Added Examples for on_confirm, cancel, on_cancel, update, on_update, status, on_status
2. Working on the Analyzing how to add new directory for validations and read about adding validations in OAS3.1
