### ISSUE TITLE
Protocol server gateway modes

### ISSUE THREAD

**Issue by joffinjoy** [beckn/protocol-server#14]
Not sure if this is clear enough from the configuration docs. 

But if I have a BAP server which is not beckn enabled, do I need two protocol-server instances to be running to connect it to beckn network?

Like
(BAP)->(Protocol Server: Client Gateway Mode)->(Protocol Server: Network Gateway Mode)->(Beckn Network including BG), or can one protocol server have both of the gateway modes enabled at the same time?

Note: This is specifically regarding V2.

**Comment by thisissandeepkumar** [comment]
There needs to be 2 instances of Protocol Server running. One as Client Gateway Mode and another as Network Gateway Mode. 

And no, both gateway modes cannot be enabled at the same time.
