### ISSUE TITLE
Protocol Server BAP Mode Schema Validation Issue

### ISSUE THREAD

**Issue by shiva-rakshith** [beckn/protocol-server#142]
When protocol server run in BAP mode and make a search request to network, it will receive multiple on_search requests from different providers. If one of the providers payload has invalid schema, protocol server is crashing and failed to process the rest of the providers requests.

Expected Outcome: If one of the providers payload is invalid, the protocol server should ignore it and process the rest of the provider requests and give the collated response back to the user.

**Comment by shreyvishal** [comment]
Have checked and done multiple round of testing and found the issue does not persist now
