### ISSUE TITLE
Certificate renewal for Beckn protocol domains

### ISSUE THREAD

**Issue by viraj89** [beckn/protocol-server#173]
## Description
The SSL certificates for the following domains are set to expire in 7 days:
- mit-bpp-healthcare.becknprotocol.io
- registry-mit.becknprotocol.io

As these certificates were not obtained from Let's Encrypt, they will not auto-renew through our Jenkins job. We have received approval to renew these certificates manually.

## Goals
- [ ] Renew SSL certificate for mit-bpp-healthcare.becknprotocol.io
- [ ] Renew SSL certificate for registry-mit.becknprotocol.io
- [ ] Ensure both domains are functioning correctly after renewal

The SSL certificates for both domains are renewed successfully, and both domains continue to function without any disruptions.

## Acceptance Criteria
- [ ] SSL certificate for mit-bpp-healthcare.becknprotocol.io is renewed
- [ ] SSL certificate for registry-mit.becknprotocol.io is renewed
- [ ] Both domains are accessible and secure after certificate renewal

## Mockups / Wireframes
N/A

## Product Name
Beckn

## Domain
NA 

## Tech Skills Needed
DevOps 

## Complexity
Medium

## Category
DevOps

## Sub Category
Certificate Management

**Comment by prasad-takale-eminds** [comment]
We have renewed the SSL cert for the mentioned domains.
