### ISSUE TITLE
Inconsistent setup doc instructions in V2

### ISSUE THREAD

**Issue by joffinjoy** [beckn/protocol-server#18]
1. In the README file, the command for starting the server is given as `npm run start`. But this script doesn't exist in the package.json of v2. This is probably an obsolete instruction from v1.

2. In the configuration guide, it is not mentioned that the file should be named `default.yaml`. I had to infer this from other configurations (Like Docker configuration). 

3. Not sure if this is fixed or not, but in client configuration section it is mentioned that `Note: In case more than one mode of communication is configured, then the mode of communication will be decided based on this priority order`. But this wasn't the case for me, whenever I had more than one mode configured in `default.yaml`, the server wouldn't start by throwing an error saying multiple clients were configured. I removed two entries to make it work. 

4. I am not sure what is happening in `Message Queue Mode Configuration`, Does the **client** in description refer to the protocol-server itself in client gateway mode? Or is this configuration related to "Message Queue" (3rd option) in client configuration? Either way, even in synchronous mode I had to setup RabbitMQ for the server to start. 

5. RabbitMQ isn't mentioned as a prerequisite.

**Comment by thisissandeepkumar** [comment]
Docs have been updated.
