### ISSUE TITLE
Add support for OpenAPI version 3.1

### ISSUE THREAD

**Issue by vbabuEM** [beckn/protocol-server#197]
In order to support Layer 2 Config, the spec team is using conditionals(if-then-else) constructs and other conditional schema constructs. These are available in the 2020-12 version of JSON Schema. However Protocol Server currently supports OpenAPI 3.0 which supports only Draft 5 of JSON Schema (8 years old), which does not have these constructs.

Upgrade Protocol Server to support OpenAPI version 3.1. Please consider this request on priority. 

cc @emmayank @viraj89 @em-abee @shreyvishal @mayurvir @ravi-prakash-v

**Comment by emmayank** [comment]
Hi @vbabuEM , you can close this issue, and i have created the same [here](https://github.com/beckn/protocol-server/issues/202)
