### ISSUE TITLE
Exploring options for JSON validation against OpenAPI version 3.1 document

### ISSUE THREAD

**Issue by rajaneeshk90** [beckn/protocol-server#204]
1. Creating validator class for validating oasis 3.1 
2. Change code to support mobility in the openAPi validator

**Comment by rajaneeshk90** [comment]
Search on the internet/GPT.
Created a node app that can do openAPI3.1 validation. support for retail only.
Tested the APP locally.
Deployed it on ec2.
Added a route which can be used to validate mobility as well in future.
redeployed.

**Comment by emmayank** [comment]
closing the issue, as duplicate already exist here - 
https://github.com/beckn/protocol-server/issues/202
