### ISSUE TITLE
[BOC Community]: test issue 2

### ISSUE THREAD

**Issue by rahul-eminds** [beckn/protocol-server#205]
## Description
[Provide a brief description of the feature, including why it is needed and what it will accomplish.]

## Goals
- [ ] [Goal 1] tee
- [ ] [Goal 2]
- [ ] [Goal 3]
- [ ] [Goal 4]
- [ ] [Goal 5]

### Implementation Details

testing it

### Product Name

Beckn Nova

### Tech Skills Needed

AWS

### Complexity

Beginner

### Category

API

**Comment by emmayank** [comment]
closing the issue as it was created for testing purpose
