### ISSUE TITLE
[BOC Community]: leaderboard test issue 3

### ISSUE THREAD

**Issue by rahul-eminds** [beckn/protocol-server#207]
## Description
[Provide a brief description of the feature, including why it is needed and what it will accomplish.]

## Goals
- [ ] [Goal 1]
- [ ] [Goal 2]
- [ ] [Goal 3]
- [ ] [Goal 4]
- [ ] [Goal 5]

### Implementation Details

test issue 3

### Product Name

Beckn Nova

### Tech Skills Needed

Artificial Intelligence

### Complexity

Beginner

### Category

Backend

**Comment by emmayank** [comment]
closing the issue, as it was created for testing purpose
