### ISSUE TITLE
Webhook mode is not working as expected

### ISSUE THREAD

**Issue by sagarinpursue** [beckn/protocol-server#21]
webhook url is configured in both protocol server client as well as network configuration.
however configured URL is not called when the responses are available.

**Comment by darshansk** [comment]
HI Sagar,

Can you please provide the config file, so that we can understand the issue better?

**Comment by avinasheminds** [comment]
@darshansk  attached config files for webhook mode.

[webhook-client.txt](https://github.com/beckn/protocol-server/files/9878041/webhook-client.txt)
[webhook-network.txt](https://github.com/beckn/protocol-server/files/9878042/webhook-network.txt)

**Comment by sagarinpursue** [comment]
@darshansk : Is there any update on this ?

**Comment by sagarinpursue** [comment]
As identified in the troubleshooting call Webhooks controller is failing to process the responses from BPPs when there is vast data in the responses.
Until that is fixed, webhook mode cannot be used.

**Comment by shreyvishal** [comment]
This is an old issue and not present in the current and active branch of the protocol-server code base. So we can close this
cc: @faizmagic @sareenEminds

**Comment by faizmagic** [comment]
@vishi24, Given that webhook mode is working as expected in our env, please provide a link to the documentation on how to configure the protocol server in webhook mode and we an close the ticket

**Comment by vishi24** [comment]
Webhook mode is tested in found to be working as expected.

Please refer https://github.com/beckn/protocol-server?tab=readme-ov-file#protocol-server-setup-guide  for installation.
