### ISSUE TITLE
Add a health check endpoint

### ISSUE THREAD

**Issue by vbabuEM** [beckn/protocol-server#224]
## Description
AWS work currently ongoing in Beckn-ONIX requires an endpoint to check the status of the server's health. Implement a health check endpoint in protocol server as below:

Endpoint: /health
Return Status code: 200
Return message format: 
The following is a sample response format from the Spring Boot framework. At a minimum have the status key in the root, even if the components dont make sense. 

{
  "status" : "UP",
  "components" : {
    "broker" : {
      "status" : "UP",
      "components" : {
        "us1" : {
          "status" : "UP",
          "details" : {
            "version" : "1.0.2"
          }
        },
        "us2" : {
          "status" : "UP",
          "details" : {
            "version" : "1.0.4"
          }
        }
      }
    },
    "db" : {
      "status" : "UP",
      "details" : {
        "database" : "H2",
        "validationQuery" : "isValid()"
      }
    },
    "diskSpace" : {
      "status" : "UP",
      "details" : {
        "total" : 77851254784,
        "free" : 38081384448,
        "threshold" : 10485760,
        "path" : "/home/runner/work/spring-boot/spring-boot/spring-boot-project/spring-boot-actuator-autoconfigure/.",
        "exists" : true
      }
    }
  }
}

**Comment by vbabuEM** [comment]
@viraj89 @emmayank @yesrag2309  Issue raised by the AWS integration work on Beckn-ONIX. Please add to your backlog.

**Comment by emmayank** [comment]
Thanks @vbabuEM  for raising the issue. assigned it to @em-abee

**Comment by emmayank** [comment]
Review Completed
