### ISSUE TITLE
Debugging BAP Protocol Server Issue

### ISSUE THREAD

**Issue by emmayank** [beckn/protocol-server#243]
## Description
Investigate and debug an issue occurring within the BAP Protocol Server. This involves identifying the root cause, examining logs, monitoring server behavior, and implementing necessary fixes. The objective is to restore the Protocol Server to stable operation, ensuring it functions correctly in handling requests and processing data.

## Goals
- [x] Analyze the reported issue within the BAP Protocol Server.
- [x] Review server logs and monitor server behavior to pinpoint the problem.
- [x] Identify the root cause of the issue and document findings.
- [x] Implement and test a fix to resolve the issue.
- [x] Ensure the Protocol Server operates smoothly after the fix, with no regressions.

## Expected Outcome
A resolution to the identified issue within the BAP Protocol Server, restoring it to stable operation and ensuring correct request handling and data processing.

## Acceptance Criteria
- [x] Root cause of the issue is identified and documented.
- [x] A fix is implemented and thoroughly tested.
- [x] The Protocol Server operates as expected post-fix, with no errors or unexpected behavior.
- [x] Monitoring confirms the issue is resolved and that the server remains stable.

## Mockups / Wireframes
NA

## Product Name
Beckn - BAP Protocol Server

## Domain
TBD

## Tech Skills Needed
- Debugging and Troubleshooting
- Log Analysis
- Protocol Server Maintenance
- Testing and Verification

## Complexity
High

## Category
Backend Development

## Sub Category
Troubleshooting

**Comment by prasad-takale-eminds** [comment]
After adding the correct to the layer 2 configs for uai domain and restarting the bap-client and bap-network issue got resolved.
