### ISSUE TITLE
Should we self host the protocol server or use the hosted version? 

### ISSUE THREAD

**Issue by karntrehan** [beckn/protocol-server#26]
Hie folks, 
We can see that there is a hosted version of the protocol server already on AWS. We were wondering if it is production ready and can be used for our usecases? Or is that just a demo deployment and we are expected to host our own version of the protocol server?

**Comment by mshar899** [comment]
@karntrehan  Were you able to find the answer for this?

**Comment by yashb042** [comment]
Following

**Comment by vishi24** [comment]
The protocol server is production-ready and being used by multiple participants. Every participant needs to setup their own instance of protocol server.
