### ISSUE TITLE
Spelling mistake for /lookupCache and /responseCache api endpoints

### ISSUE THREAD

**Issue by Harshroxnox** [beckn/protocol-server#27]
In the protocol.ts file under the directory `/src/routes/protocol.ts` 
on line 60 and line 72 there is a spelling mistake 
`/lookupCache` is spelled as `/lookupCacbe`
https://github.com/beckn/protocol-server/blob/20c2be50dba396e6e4f9a9799e676eec41ee1c0b/src/routes/protocol.ts#L60
`/responseCache` is spelled as `/responseCacbe`
https://github.com/beckn/protocol-server/blob/20c2be50dba396e6e4f9a9799e676eec41ee1c0b/src/routes/protocol.ts#L72

**Comment by Harshroxnox** [comment]
#28

**Comment by utkars3** [comment]
@mentors I want to work on this issue
