### ISSUE TITLE
Kubernetes deployment scripts for Protocol server

### ISSUE THREAD

**Issue by vishi24** [beckn/protocol-server#45]
**Name: protocol-server
Title: "Kubernetes Deployment script"**

**Description**

The protocol server has docker-based deployment scripts but there are no scripts that can be used to deploy the protocol server on Kubernetes. Need to write Kubernetes script which can be used in production environment for deployment.

**Goals:**
Create Kubernetes script for protocol server deployment.

**Expected Outcome:**
Working scripts for deployment of the protocol server on Kubernetes.

**Acceptance Criteria:**
Working scripts for deployment of the protocol server on Kubernetes.

**Project:**
Beckn

Organization Name:
Beckn Open Collective

Domain:
Others

**Tech Skills Needed:**
• Understanding of protocol server
• Nodejs
• Docker
• Kubernetes
• Basic understanding of rabbitMQ and Redis

**Comment by nitishmalang** [comment]
Hi @vishi24 can I work on this issue basically 
we have to create Deployment files for each service (MongoDB, Redis, RabbitMQ) potentially for the Beckn Protocol Server itself

**Comment by RISHIKESHk07** [comment]
@faizmagic is this open would give it a try ?

**Comment by RISHIKESHk07** [comment]
@faizmagic is this issue open still ?

**Comment by vishi24** [comment]
@RISHIKESHk07 , this is open you can give it a try.

**Comment by vishi24** [comment]
The issue has been transferred to ONIX, thus necessitating the closure of this issue.
