### ISSUE TITLE
Docker-compose for protocol server deployment

### ISSUE THREAD

**Issue by vishi24** [beckn/protocol-server#46]
**Name: protocol-server
Title: "Docker-compose for protocol server deployment"**

**Description**

The protocol server has docker-based deployment scripts that deploy the required infra (redis,rabbitMQ) but there are no scripts that can be used to deploy the application on the server. Need to create a single Docker-compose file that can be used to used to deploy infra and the services in a single command. It should have .env file also in which configuration parameters can be set.

**Goals:**
Single docker-compose file for deploying infra and protocol server services.

**Expected Outcome:**
Working docker-compose file for the deployment of the required infra and protocol server on docker.

**Acceptance Criteria:**
Working docker-compose file for the deployment of the required infra and protocol server on docker.

**Project:**
Beckn

Organization Name:
Beckn Open Collective

Domain:
Others

**Tech Skills Needed:**
• Understanding of protocol server
• Nodejs
• Docker
• • Basic understanding of rabbitMQ and Redis

**Comment by RISHIKESHk07** [comment]
@faizmagic would like give it a try ?

**Comment by vishi24** [comment]
Docker-compose for Infra - https://github.com/beckn/protocol-server/blob/devops/docker/docker-compose.yml
Docker-compose that includes docker image - https://github.com/beckn/beckn-utilities/blob/main/onix-installer/docker-compose-v2.yml
