### ISSUE TITLE
Protocol Server Videos  Production setup (VM instance)

### ISSUE THREAD

**Issue by vishi24** [beckn/protocol-server#58]
**Name**: protocol-server
**Title**: "Improve documentation for Protocol server"

**Description**
Current documentation is in textual format, there is no video content available for the implementors that can give them a better understanding and more clarity to do a setup on the Production environment.

**Goals:**
Creation of video documentation for protocol Server.

**Expected Outcome:**
Individual small videos (max 7 mins) to be created for each of the topics.

1. BAP setup   
2. BPP setup
3. Registering on BECKN registry
4. Postman testing with a specific domain
5. Setting up HA proxy
6. Applying SSL using OpenSSL
7. Debugging video and explanation, specifically for protocol server

**Project:**
Beckn

**Organization Name:**
Beckn Open Collective

**Domain:**
Others

**Tech Skills Needed:**

• AWS
• Understanding of protocol server
• Docker

**Comment by mayurvir** [comment]
Improvement request:

When we create any updated videos, can we ensure that there is an audio based instructions as well?
