### ISSUE TITLE
Telemetry Generation

### ISSUE THREAD

**Issue by shiva-rakshith** [beckn/protocol-server#67]
As per Beckn protocol, only search API call goes through gateway and rest of the API calls are peer-to-peer. Generating telemetry and sending to network facilitator or manager will help to get complete visibility of the network.

Generate telemetry for each API request and send to telemetry server. Pushing telemetry events to telemetry server can be in batches or based on time interval (which ever is earlier).

**Comment by vbabuEM** [comment]
https://github.com/beckn/protocol-server/pull/62
https://github.com/beckn/protocol-server/pull/66
