### ISSUE TITLE
Intermittently Getting Failed call to Subscriber Error

### ISSUE THREAD

**Issue by shiva-rakshith** [beckn/protocol-server#68]
A network participant is running the protocol server as BPP, intermittently getting below error, even though subsriber system is up and running fine.

```
2024-01-17T09:11:38.855Z [test] error: Result : Failed call to Subscriber, 
```

**Comment by vishi24** [comment]
> A network participant is running the protocol server as BPP, intermittently getting below error, even though subsriber system is up and running fine.
> 
> ```
> 2024-01-17T09:11:38.855Z [test] error: Result : Failed call to Subscriber, 
> ```

Need more details -
1. Where are you getting this error - BPP-PS-client or BPP-PS-network?  
2. What is the subscriber system here? 
3. Is this specific for a BAP?

**Comment by faizmagic** [comment]
@vishi24 , looks like this issue does not exist in our env, if we encounter this issue, we will re-open.
