### ISSUE TITLE
Handling Unsolicited Responses - Handling of asynchronous on_status messages when BAP is configured in the synchronous mode

### ISSUE THREAD

**Issue by vbabuEM** [beckn/protocol-server#71]
## Description
Beckn protocol allows the BPP to send on_status messages even without a status call. The typical usecases for these are to inform the BAP of the status of the packages. When the BAP is configured to work in synchronous mode, currently it looks like there is no way for the client to get called back when these on_status messages are received. (While we can argue that the client can trigger a status message and get the same info in on_status in a synchronous fashion, one usecase which will be difficult to cover in such scenario is to implement notifications of delivery agent being at the delivery location). 

## Goals
When the client has configured the BAP in a synchronous mode, there should be a mechanism where it can get the unsolicited on_status messages sent by BPP.

## Expected Outcome
One option is to add a new web_hook that can be configured by the client. It will receive unsolicited messages there. The rest of the synchronous communication between client and the BAP can remain as is. 

## Acceptance Criteria

- When the BAP is configured in synchronous mode, there should be an additional configurable webhook that will receive unsolicited messages sent by BPP.

**Comment by faizmagic** [comment]
@vbabuEM , need help in defining the approach.

**Comment by vbabuEM** [comment]
I can think of two approaches. 
One is the traditional flow and the BAP client will finally call a webhook to relay the message. I think this approach is a bit complicated in both configuration as well as implementation. Basically the complexity here is in distinguishing unsolicited messages in different client configurations(webhook/synchronous)
The second approach is where the BAP network directly calls the webhook for unsolicited messages. This is easy to implement, keeps the current flow intact and only requires very little change. I think the BAP network already has cache data to identify if the current message is solicited or unsolicited. Right now I think it sends back a NACK for unsolicited. All we might have to do is if the configuration says that it should be handled and a webhook has been configured for unsolicited messages, it directly calls it.  This is a bit unconventional, but easy to implement I feel. 

@faizmagic , @shreyvishal , @em-abee , what do you think?

**Comment by vbabuEM** [comment]
@faizmagic I forgot that I had already proposed some solutions. I am surprised I had proposed the second approach above. Today I was only thinking about the first one. Please let me know what you think. The first approach is probably better from the sense that we wont be introducing something totally new. Once we finalize on this, I will write the detailed spec. 
cc @shreyvishal @em-abee

**Comment by vbabuEM** [comment]
Here are the final requirements for Protocol Server. (There will be a new issue for Generic Client layer):
1. BAP Client should support a new webhook configuration for unsolicited messages. It is optional
2. Unsolicited messages should make their way all the way from BPP Client till BAP Client. There are many places in the code where we use RequestCache and flag messages without cache entry. These should be modified to allow for unsolicited messages.
3. Once unsolicited message comes into BAP Client, it should call the webhook if configured. It can probably ignore if not configured.

This should work irrespective of the mode of the BAP client. Even if the BAP client is in synchronous mode, the webhook configuration should be available. If the BAP client is in async mode, the user of BAP client can decide to configure both this as well as existing webhook to same endpoint or different endpoints.

**Comment by em-abee** [comment]
1. Proposed Solution for Transmitting Unsolicited Messages from BPP Client to BAP Client:

- Implement caching mechanisms in both BPP and BAP networks to store request timestamps and TTL values in Redis.
- Extend the cache expiry time to 1 hour to accommodate potential message delays.
- Upon receiving a message, check if it exists in the cache. If not found, treat it as an unsolicited message and forward it to the BAP network.
- Calculate the time difference between the current timestamp and the cached timestamp. If the difference is less than the TTL, consider it a valid message and forward it to the BAP network.
- Ignore if the time difference is greater than TTL
- Similar implementations should be applied on the BAP network side to handle unsolicited messages.
- Invoking the Client Webhook:

2. Upon receiving an unsolicited message, the BAP Client should check if a webhook is configured.

- If a webhook is configured, call it to notify the client about the unsolicited message.
- If no webhook is configured, the BAP Client can choose to ignore the unsolicited message.

**Comment by em-abee** [comment]
PR - https://github.com/beckn/protocol-server/pull/123

**Comment by faizmagic** [comment]
@vbabuEM , can you please review the PR

**Comment by vbabuEM** [comment]
@faizmagic , it has been reviewed and merged yesterday.
