### ISSUE TITLE
Getting authentication error while connecting to RabbitMQ

### ISSUE THREAD

**Issue by sreekanthmr** [beckn/protocol-server#85]
I'm trying to setup latest release of protocol server.  I have made all configuration changes as mentioned in the documentation and completed all installation steps.  When I try running the protocol server I get authentication error with RabbitMQ.  I'm able to login to RabbitMQ from management interface though.

**Comment by vishi24** [comment]
@sreekanthmr Can you please provide update on this ?

**Comment by sreekanthmr** [comment]
@vishi24 Looks like the sample yml file in the config has an issue.  I changed default.yml to the one I had from the earlier version and the issue got resolved.

**Comment by vishi24** [comment]
The user has to provide the corect credentials in the yml files for accessing rabbitMQ/Redis. The values in sample config files are only placeholders.

**Comment by sreekanthmr** [comment]
Of course we did those changes.  In spite of that, it wasn't working.  We just replaced the file with what we had earlier and that solved the issue.  We didn't find the time to investigate that further.
