### ISSUE TITLE
ACK/NACK enum implementation in the Ack of requests in Protocol Server

### ISSUE THREAD

**Issue by vbabuEM** [beckn/protocol-server#94]
Protocol Spec says the following about the Ack we send to requests on BPP and on_* on BAP. 

"The status of the acknowledgement. If the request passes the validation criteria of the BPP, then this is set to ACK. If a BPP responds with status = `ACK` to a request, it is required to respond with a callback. If the request fails the validation criteria, then this is set to NACK. Additionally, if a BPP does not intend to respond with a callback even after the request meets the validation criteria, it should set this value to `NACK`."

When we receive the request we should do signature validation and schema validation before we send back the Ack. And the Ack should have the right enum value(ACK/NACK) and error value if the validation(also schema validation) fails. 

Please check the PS code to ensure this is properly implemented.

If this is not correctly implemented, necessary enhancements needs to be done to get it right as part of the specification

Please test the ACK/NACK responses by directly making a request to gateway/BPP without passing from the BAP protocol server.

Make request with an invalid signature.
Make request without header.
Make request with valid signature and invalid request body.
Make request with valid signature and valid request body.

**Comment by shreyvishal** [comment]
Current Status: Done with analysis of this issue and found that the there are two points in this issue. 
1. ACK and NACK should be sent after proper validation.
2. If the BPP side data source application is not able to send the response then it should sent a NACK to the BAP side.

So the 1st point is already implemented. And the 2nd point is not applicable for our current protocol server architecture, it is applicable for BPPs that are not using our protocol server instead using any other techstack.

cc: @vishi24 @vbabuEM

**Comment by vishi24** [comment]
@shreyvishal , Please test the ACK/NACK responses by directly making a request to gateway/BPP without passing from the BAP protocol server.
1. Make request with an invalid signature.
2. Make request without header.
3. Make request with valid signature and invalid request body.
4. Make request with valid signature and valid request body.

**Comment by shreyvishal** [comment]
![Uploading Screenshot 2024-03-12 at 4.14.45 PM.png…](Outcomes of different Use Cases)
cc: @vishi24

**Comment by vishi24** [comment]
@shreyvishal , Please check if the ACK/NACK is sent back after the validation of the signature/request payload or it is sent as soon as the request is received.
Also, attach the payload collection you have used to test these use cases.

**Comment by shreyvishal** [comment]
@vishi24, I have checked the ACK is sent only after the validation of the signature, but NACK is sent back at multiple stages of the validations.

`{
    "context": {
        "domain": "dsep:jobs",
        "action": "search",
        "version": "1.1.0",
        "bap_id": "shreyvishal",
        "bap_uri": "https://d23e-2401-4900-1c2c-8fff-00-98-aead.ngrok-free.app",
        "location": {
            "country": {
                "name": "India",
                "code": "IND"
            },
            "city": {
                "name": "Bangalore",
                "code": "std:080"
            }
        },
        "transaction_id": "a9aaecca-10b7-4d19-b640-b047a7c60008",
        "message_id": "233b9f68-7661-461a-8fbd-dc37fa7ac32f",
        "timestamp": "2023-02-06T09:55:41.161Z"
    },
    "message": {
        "intent": {
            "fulfillment": {
                "start": {
                    "location": {
                        "gps": "19.94815,73.84124"
                    }
                },
                "end": {
                    "location": {
                        "gps": "20.00882,73.81456"
                    }
                }
            },
            "item": {
                "descriptor": {
                    "name": "Analytics - Senior Analyst"
                }
            }
        }
    }`

**Comment by faizmagic** [comment]
@vbabuEM , re-opening this ticket as this needs further verifications.

**Comment by vbabuEM** [comment]
Here are the observations.
1. The PS on BPP sends back NACK in cases where the message is wrong or cant be processed. This is as per the Protocol Spec.
2. The BAP-Network receives the NACK, however it does not transfer it back to BAP-Client properly. Due to this BAP-Client does not get back the error and it waits for the timeout and returns back an empty array. This is a bug. I have raised an issue to fix it.
https://github.com/beckn/protocol-server/issues/151
