### ISSUE TITLE
Transaction ID and Message ID clarifications

### ISSUE THREAD

**Issue by vishi24** [beckn/protocol-server#99]
## Description

There is a lot of confusion for transaction ID and message ID, we need to add below details about the transaction ID and message ID .

1. Use of transaction ID and message ID.
2. Are these IDs mandatory or optional, if mandatory in specific cases need to mention those details.
3. What is the format of these IDs and how are they being used at the infra level i.e - Redis / MongoDB / RabbitMQ.

**In main read me file at the bottom add a section "Frequently Asked Questions" and add these details there.**

## Goals

- [ ] Complete clarity for the implementors on transaction ID and message ID

## Expected Outcome

FAQ section with complete details about message and transaction ID.

## Acceptance Criteria

- [ ] FAQ section populated with the requested details.

## Implementation Details

NA

## Mockups / Wireframes

NA

---

### Product Name

Protocol Server

### Project Name

Protocol Server

### Tech Skills Needed:

Protocol server understanding

### Complexity

Low

### Category

Documentation

### Sub Category

Documentation

**Comment by vishi24** [comment]
@shreyvishal , Can you mention PR / Proof of work.

**Comment by vbabuEM** [comment]
Shreya has added an entry in FAQ explaining the difference.

**Comment by vbabuEM** [comment]
[Readme File](https://github.com/beckn/protocol-server/blob/master/README.md) contains the FAQ entries
